import SchemeCard from './SchemeCard'
import SummaryBanner from './SummaryBanner'

function ResultsSection({ result, profile, onSchemeSelect }) {
  return (
    <div style={{ marginTop: 40 }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline', marginBottom: 20 }}>
      <h2 style={{
        fontFamily: 'var(--font-head)',
        fontWeight: 700,
        fontSize: 22,
        color: 'var(--text)',
          letterSpacing: '-0.03em',
        }}>
          Top {result.schemes?.length || 0} Recommendations
        </h2>
        {profile && (
          <div style={{ fontFamily: 'var(--font-mono)', fontSize: 11, color: 'var(--text3)' }}>
            ৳{profile.monthly_investment.toLocaleString()} · {profile.time_range_years}yr · {profile.risk_level} risk
          </div>
        )}
      </div>

      {result.summary && <SummaryBanner summary={result.summary} />}

      <p style={{ fontFamily: 'var(--font-mono)', fontSize: 11, color: 'var(--text3)', marginBottom: 16 }}>
        Click any card (or hit Enter/Space with focus) to open a chat and ask about a scheme.
      </p>

      <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
        {(result.schemes || []).map((scheme, index) => (
          <SchemeCard
            key={scheme.scheme_id}
            scheme={scheme}
            rank={index + 1}
            onSelect={onSchemeSelect}
          />
        ))}
      </div>

      <div style={{
        marginTop: 32,
        padding: '16px 20px',
        background: 'var(--surface)',
        border: '1px solid var(--border)',
        borderRadius: 10,
      }}>
        <p style={{ fontFamily: 'var(--font-mono)', fontSize: 11, color: 'var(--text3)', lineHeight: 1.6 }}>
          ⚠️ <strong style={{ color: 'var(--text2)' }}>Disclaimer:</strong> These recommendations are generated by AI using publicly available data (2024–2025). Projected returns are estimates only. Consult a licensed financial advisor before investing. Interest rates are subject to change.
        </p>
      </div>
    </div>
  )
}

export default ResultsSection
